PE_or_SE: PE

ref:
  # path/to/reference/gDNA.fasta
  sequence:       /secondary/projects/bbc/research/prep_bbc_shared/data/mm10_gencode/sequence/mm10_gencode.fa
  # path/to/STAR/index/directory
  index:          /secondary/projects/bbc/research/prep_bbc_shared/data/mm10_gencode/indexes/bwa/
  # path/to/gtf/file/with/transcripts.gtf
  annotation:     /secondary/projects/bbc/research/prep_bbc_shared/data/mm10_gencode/annotation/mm10_gencode.gtf

report: 2020-09-21_PFEG-20200427-CDseq_UVB-2
