PE_or_SE: PE

ref:
  # path/to/reference/gDNA.fasta
  sequence:       /secondary/projects/bbc/research/prep_bbc_shared/data/hg19_gencode/sequence/hg19_gencode.fa
  # path/to/bwa 
  index:          /secondary/projects/bbc/research/prep_bbc_shared/data/hg19_gencode/indexes/bwa/hg19_gencode
  # path/to/gtf/file/with/transcripts.gtf
  annotation:     /secondary/projects/bbc/research/prep_bbc_shared/data/hg19_gencode/annotation/hg19_gencode.gtf

report: 2021-Jan-26_PFEG-CDseq_CPD
